name: IP Range Processor

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering
  push:
    branches:
      - main

jobs:
  process-ips:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Add this line to grant write permissions
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0  # Needed to push back changes
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        
    - name: Run IP processor
      run: |
        python scripts/ip_processor.py
        
    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add ir.txt
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update IP range files [skip ci]" && git push)
